name: Package

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: package-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  arch:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/arch-package.yml@a231338c970c58b345133223d3bd8df502331c95
  rpm:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/rpm-check.yml@a231338c970c58b345133223d3bd8df502331c95
    with:
      spec-name: waybar-workspace-buttons
