name: Package

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: package-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  arch:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/arch-package.yml@429e647539b02e85ea59b38c441f83a86ee77835
  rpm:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/rpm-check.yml@429e647539b02e85ea59b38c441f83a86ee77835
    with:
      spec-name: waybar-workspace-buttons
