name: Package

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: package-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  arch:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/arch-package.yml@43f34aaaa95951ebf71e625de3cf1207e2a259e6
  rpm:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/rpm-check.yml@43f34aaaa95951ebf71e625de3cf1207e2a259e6
    with:
      spec-name: waybar-workspace-buttons
