name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/release.yml@a231338c970c58b345133223d3bd8df502331c95
    secrets: inherit
    with:
      spec-name: waybar-workspace-buttons
