name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/release.yml@89a6561a85e21ca8425dbdace40d115c0bbc852d
    secrets: inherit
    with:
      spec-name: waybar-workspace-buttons
